import Head from "next/head";
import Header from "@/components/Header";
import { useEffect, useState } from "react";
import { IContentAbout } from "@/types/IContentAbout";
import { en, ptBr } from "@/content/About.data";
import { IDefaultProps } from "@/types/IDefaultProps";

export default function About({ ...props }: IDefaultProps) {
  const [content, setContent] = useState<IContentAbout>(ptBr);

  useEffect(() => {
    setContent(props.lang === "ptBr" ? ptBr : en);
  }, [props.lang]);

  return (
    <>
      <Head>
        <title>{content.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header path={content.path} />
      </main>
    </>
  );
}
